"""email verification fields

Revision ID: 79705033c878
Revises: ccf16b86ddfe
Create Date: 2025-08-29 01:13:08.353338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79705033c878'
down_revision = 'ccf16b86ddfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verify_code_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verify_code_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verify_code_expires_at')
        batch_op.drop_column('verify_code_hash')
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
